# Python Function App to Linux on Azure
# Build a Python function app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

variables:
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  # Working Directory = racine du repo
  workingDirectory: '$(Build.SourcesDirectory)'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - checkout: self
      fetchDepth: 0

    # Préparation SonarCloud
    - task: SonarCloudPrepare@3
      displayName: 'Prepare SonarCloud analysis'
      env:
        SONAR_TOKEN: $(SONAR_TOKEN)
      inputs:
        SonarCloud: 'SF-SonarCloud'          # Nom du service connection SonarCloud
        organization: 'sonarcloudtools'      # Ton organization SonarCloud
        scannerMode: 'cli'
        configMode: 'manual'
        cliProjectKey: 'DBS.SalesForce'
        cliProjectName: 'DBS.SalesForce'
        sonarToken: '$(SONAR_TOKEN)'
        # Chemin vers les classes à analyser, relatif à la racine du repo
        cliSources: 'force-app/main/default/classes'

    # Analyse SonarCloud
    - task: SonarCloudAnalyze@3
      displayName: 'Run SonarCloud analysis'
      env:
        SONAR_TOKEN: $(SONAR_TOKEN)
      inputs:
        jdkversion: 'JAVA_HOME_21_X64'

    # Build des extensions .NET si le projet existe
    - bash: |
        if [ -f extensions.csproj ]
        then
            dotnet build extensions.csproj --runtime ubuntu.22.04-x64 --output ./bin 
        fi
      workingDirectory: $(workingDirectory)
      displayName: 'Build extensions'

    # Archive des fichiers
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(workingDirectory)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    # Publication de l’artifact
    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop
